apiVersion: skaffold/v4beta6
kind: Config

build:
  local:
    push: true # <- We need to push the images so Cloud Run can deploy them

  platforms: ["linux/amd64"] # <- Specific platform supported by Cloud Run

  artifacts:
    - image: us-west1-docker.pkg.dev/YOUR_PROJECT_ID/cloud-run-source-deploy/helloworld # <- Should match the image name in the Cloud Run service.yaml
      docker:
        dockerfile: ./Dockerfile

manifests:
  rawYaml:
    - resources/service.yaml

deploy:
  cloudrun:
    projectid: YOUR_PROJECT_ID
    region: us-west1

# Added to change local port used
portForward:
  - resourceType: service
    resourceName: cloud-run-service-name
    localPort: 9001